// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdqdudvdfaarbjwwfaqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcWR1ZHZkZmFhcmJqd3dmYXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjE2NDksImV4cCI6MjA2ODQzNzY0OX0.d04WObnZgxwP3IrC3Kt6D9O14VR8RZwgUQQhmJjpRcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});